version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
  api:
    build: ./api
    container_name: api
    ports:
      - "5001:5001"
    volumes:
      - ./api:/app
      - /app/node_modules
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/web
  web:
    build: ./web
    container_name: web
    ports:
      - "5000:5000"
    volumes:
      - ./web:/app
      - /app/node_modules
    depends_on:
      - mongo
      - api
    stdin_open: true
    tty: true
    environment:
      MONGO_URI: mongodb://mongo:27017/web
  volumes:
    data: